USE [master]
GO

/****** Object:  Database [bancomvc]    Script Date: 09/12/2020 04:35:17 ******/
CREATE DATABASE [bancomvc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bancomvc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\bancomvc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bancomvc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\bancomvc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bancomvc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bancomvc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bancomvc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bancomvc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bancomvc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bancomvc] SET ARITHABORT OFF 
GO

ALTER DATABASE [bancomvc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bancomvc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bancomvc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bancomvc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bancomvc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bancomvc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bancomvc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bancomvc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bancomvc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bancomvc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bancomvc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bancomvc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bancomvc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bancomvc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bancomvc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bancomvc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bancomvc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bancomvc] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bancomvc] SET  MULTI_USER 
GO

ALTER DATABASE [bancomvc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bancomvc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bancomvc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bancomvc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bancomvc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bancomvc] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bancomvc] SET  READ_WRITE 
GO


