USE [bancomvc]
GO

/****** Object:  Table [dbo].[usuarios]    Script Date: 09/12/2020 04:36:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](50) NULL,
	[usuario] [varchar](50) NULL,
	[senha] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE produtos(
id INT PRIMARY KEY IDENTITY NOT NULL,
nome VARCHAR(50),
descricao VARCHAR(100),
valor NUMERIC(18,2)
)


